ci sixth error check

diff --git a/examples/bare_etiss_processor/run_helper.sh.in b/examples/bare_etiss_processor/run_helper.sh.in
--- a/examples/bare_etiss_processor/run_helper.sh.in
+++ b/examples/bare_etiss_processor/run_helper.sh.in
@@ -112,3 +112,11 @@ else
 fi
 
 rm $DYN_INI
+
+cd "$some_directory"
+if [ "$?" = "0" ]; then
+  rm *
+else
+  echo "Cannot change directory!" 1>&2
+  exit 1
+fi
